[tool.poetry]
name = "task-manager"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.5"
psycopg = "^3.2.4"
django-extensions = "^3.2.3"
django-debug-toolbar = "^5.0.1"
psycopg2-binary = "^2.9.10"
werkzeug = "^3.1.3"
djangorestframework = "^3.15.2"
django-storages = "^1.14.5"
boto3 = "^1.37.1"
markdown = "^3.7"
bleach = "^6.2.0"
django-widget-tweaks = "^1.5.0"
pillow = "^11.1.0"
django-redis = "^5.4.0"
pyopenssl = "^25.0.0"
django-csp = "^3.8"
argon2-cffi = "^23.1.0"
black = "^25.1.0"
django-ninja = "^1.4.0"
pyjwt = "^2.10.1"
django-ratelimit = "^4.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
