apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanager-settings
  namespace: taskmanager
data:
  ALLOWED_HOSTS: 'localhost,127.0.0.1,taskmanagerapp-service'
  DB_HOST: "postgres"
  DB_NAME: "task_manager"
  DB_PORT: "5432"
  DB_USER: "siddhesh" 
  DEBUG: "False"
  DJANGO_SETTINGS_MODULE: taskmanager.production
  REDIS_LOCATION: "redis://redis-0.redis.taskmanager.svc.cluster.local/1"