apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  namespace: taskmanager
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taskmanagerapp
  template:
    metadata:
      labels:
        app: taskmanagerapp
    spec:
      containers:
        - name: django-app
          image: siddheshparave16/web_applications_django:latest
          ports:
            - containerPort: 8000
          envFrom: 
            - configMapRef:
                name: taskmanager-settings
            - secretRef:
                name: taskmanager-db-secret
          env:
            - name: POSTGRES_HOST
              value: "localhost,127.0.0.1,0.0.0.0,django-app-deployment.taskmanager.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: DJANGO_SETTINGS_MODULE
              value: "taskmanager.production"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health/liveness/
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health/readiness/
              port: 8000
            initialDelaySeconds: 40
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 3



