apiVersion: v1
kind: Service
metadata:
  name: taskmanagerapp-service
  namespace: taskmanager  
spec:
  type: NodePort
  selector:
    app: taskmanagerapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000