# Generated by Django 5.1.6 on 2025-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                    ("ARCHIVED", "Archived"),
                ],
                db_comment="Can be Assigned, In Progress, Done, or Archived",
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
    ]
