# Generated by Django 5.1.6 on 2025-04-14 02:53

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                # Keep your existing null/blank settings
                null=True,
                blank=True,
                db_column="owner_id",
            ),
        ),
    ]
