# Generated by Django 5.1.6 on 2025-04-14 03:03

from django.db import migrations, models
from django.db.migrations.operations.special import RunSQL
from django.conf import settings


def forwards_func(apps, schema_editor):
    """Optional data migration to fix existing relationships"""
    Task = apps.get_model("tasks", "Task")
    TaskManagerUser = apps.get_model("accounts", "TaskManagerUser")

    for task in Task.objects.filter(owner__isnull=False):
        if not TaskManagerUser.objects.filter(id=task.owner_id).exists():
            task.owner = None
            task.save()


def reverse_func(apps, schema_editor):
    pass  # Optional reverse migration


class Migration(migrations.Migration):
    atomic = True  # For transactional safety

    dependencies = [
        ("tasks", "0003_fix_owner_foreign_key"),  # Last applied tasks migration
        ("accounts", "0004_authtoken"),
    ]

    operations = [
        # First remove the constraint via SQL
        RunSQL(
            sql="ALTER TABLE tasks_task DROP CONSTRAINT IF EXISTS tasks_task_owner_id_db3dcc3e_fk_auth_user_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Then alter the field to point to the correct model
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                null=True,
                blank=True,
                db_column="owner_id",  # Keep existing column name
            ),
        ),
        # Finally add the new constraint via SQL
        RunSQL(
            sql="ALTER TABLE tasks_task ADD CONSTRAINT tasks_task_owner_id_fk "
            + "FOREIGN KEY (owner_id) REFERENCES accounts_taskmanageruser(id) "
            + "DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE tasks_task ADD CONSTRAINT tasks_task_owner_id_db3dcc3e_fk_auth_user_id "
            + "FOREIGN KEY (owner_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;",
        ),
    ]
