# Generated by Django 5.1.6 on 2025-04-22 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_fix_creator_relations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epic",
            name="sprints",
        ),
        migrations.AddField(
            model_name="epic",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="epics", to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sprints",
                to="tasks.epic",
            ),
        ),
        migrations.AlterField(
            model_name="epic",
            name="creator",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_epics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="creator",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_sprints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_comment="Foreign key to the User who currently owns the task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
