# Generated by Django 5.1.6 on 2025-02-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial_squashed_0007_task_due_date_task_due_date_after_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='sprints',
            field=models.ManyToManyField(related_name='epics', to='tasks.sprint'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_comment='Can be High, Medium, Low', default='LOW', max_length=20),
        ),
    ]
