# Generated by Django 5.1.6 on 2025-03-04 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_epic_sprints_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='tasks.task')),
            ],
        ),
    ]
