# Generated by Django 5.1.6 on 2025-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_file_upload_task_image_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formsubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
    ]
