version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: siddhesh
      POSTGRES_DB: task_manager
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - my-network
    volumes:
      - ./mailhog-data:/maildir
    environment:
      MH_MAILDIR_UID: 1000
      MH_MAILDIR_GID: 1000
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    user: "1000:1000"

volumes:
  postgres-data:
  redis_data:

networks:
  my-network:
    driver: bridge